import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import classNames from 'classnames';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const getEUkraineFontPath = (fontType: string) =>
  `./fonts/e-Ukraine/e-Ukraine-${fontType}.otf`;

const eUkraineHeadFont = localFont({
  src: './fonts/e-Ukraine-Head/e-UkraineHead-LOGO.otf',
  display: 'swap',
  variable: '--eUkraineHeadLogo',
});

const eUkraineFont = localFont({
  src: [
    {
      path: './fonts/e-Ukraine/e-Ukraine-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/e-Ukraine/e-Ukraine-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--eUkraine',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={classNames(
          inter.className,
          eUkraineHeadFont.variable,
          eUkraineFont.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
